# Generated by Django 5.2.5 on 2025-08-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadra', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_tabela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DISP', 'Disponível'), ('RESV', 'Reservado'), ('VEND', 'Vendido')], default='DISP', max_length=4)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.empreendimento')),
            ],
            options={
                'unique_together': {('empreendimento', 'quadra', 'numero')},
            },
        ),
    ]
