services:
  - type: web
    name: lotesys
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file -"  # será substituído pelo Procfile
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      # O Render injeta RENDER_EXTERNAL_HOSTNAME automaticamente; o settings.py usa isso para ALLOWED_HOSTS/CSRF
      - key: DATABASE_URL
        fromDatabase:
          name: lotesys-db
          property: connectionString

databases:
  - name: lotesys-db
    plan: free
    region: oregon