services:
  - type: web
    name: lotesys
    env: python
    region: oregon
    plan: free

    # 1) Instala as dependências e coleta estáticos no build
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || true

    # 2) No start: migra e sobe o gunicorn
    startCommand: ./start.sh

    autoDeploy: true

    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
      # Se você ainda NÃO estiver usando banco externo, mantenha SQLite.
      # Quando for usar Postgres, adicione DATABASE_URL aqui:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: lotesys-db
      #     property: connectionString

# Se quiser Postgres Free depois, descomente:
# databases:
#   - name: lotesys-db
#     plan: free
#     region: oregon