services:
  - type: web
    name: lotesys
    runtime: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || true

    startCommand: ./start.sh
    autoDeploy: true

    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: ALLOWED_HOSTS
        value: "lotesys.onrender.com,127.0.0.1,localhost"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://lotesys.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: lotesys-db
          property: connectionString
      - key: SERVE_MEDIA
        value: "True"
      - key: TELEGRAM_BOT_TOKEN
        value: "8390754722:AAH_lZ6D0Xl9lZVJkmYyebRLKvX8Vpqp2_o"
      - key: TELEGRAM_CHAT_IDS
        value: "842553869"

    disks:
      - name: media
        mountPath: /opt/render/project/src/media
        sizeGB: 1

  # === CRON JOB de teste (rodando a cada 5 min) ===
  - type: cron
    name: avisos-telegram-debug
    runtime: python
    region: oregon
    plan: free
    schedule: "*/5 * * * *"   # a cada 5 minutos

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    # use --force --debug para ver mensagens mesmo sem regra de 2 em 2 dias
    startCommand: python manage.py avisos_telegram --force --debug

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false     # use os valores já definidos no serviço, ou preencha aqui
      - key: TELEGRAM_CHAT_IDS
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

databases:
  - name: lotesys-db
    plan: free
    region: oregon