services:
  - type: web
    name: lotesys
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || true

    startCommand: ./start.sh
    autoDeploy: true

    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true

      # Cria admin automático (opcional)
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123

      # Host/CSRF do Render
      - key: ALLOWED_HOSTS
        value: "lotesys.onrender.com,127.0.0.1,localhost"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://lotesys.onrender.com"

      # Postgres Free do Render
      - key: DATABASE_URL
        fromDatabase:
          name: lotesys-db
          property: connectionString

      # Habilita servir /media/ via Django no Render
      - key: SERVE_MEDIA
        value: "True"

    # Monta um disco persistente na pasta do MEDIA_ROOT
    disks:
      - name: media
        mountPath: /opt/render/project/src/media
        sizeGB: 1   # pode ajustar depois

databases:
  - name: lotesys-db
    plan: free
    region: oregon