services:
  - type: web
    name: lotesys
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || true

    startCommand: ./start.sh
    autoDeploy: true

    envVars:
      # Django
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true

      # (Opcional) Criar admin automaticamente no primeiro boot
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123

      # Host/CSRF — você já cobre no settings o RENDER_EXTERNAL_HOSTNAME.
      # Manter estes dois ajuda a não quebrar se o hostname fixo mudar.
      - key: ALLOWED_HOSTS
        value: "lotesys.onrender.com,127.0.0.1,localhost"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://lotesys.onrender.com"

      # Servir /media/ no Render (só ative se tiver disco persistente OU usar storage externo)
      - key: SERVE_MEDIA
        value: "True"

      # Postgres Free do Render
      - key: DATABASE_URL
        fromDatabase:
          name: lotesys-db
          property: connectionString

databases:
  - name: lotesys-db
    plan: free
    region: oregon