# render.yaml
services:
  - type: web
    name: lotesys
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --log-file -
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        # Render injeta o hostname público nessa variável:
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: DATABASE_URL
        fromDatabase:
          name: lotesys-db
          property: connectionString

databases:
  - name: lotesys-db
    plan: free
    region: oregon