# Generated by Django 5.2.5 on 2025-09-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato hexadecimal para o card (ex: #007bff)', max_length=7, verbose_name='Cor (hex)')),
                ('icone', models.CharField(default='fas fa-question-circle', help_text='Classe do ícone FontAwesome (ex: fas fa-question-circle)', max_length=50, verbose_name='Ícone FontAwesome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Pergunta')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta')),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada')], default='pendente', max_length=20, verbose_name='Status')),
                ('publica', models.BooleanField(default=True, help_text='Se marcado, a pergunta será visível para todos os usuários', verbose_name='Pública')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.categoria', verbose_name='Categoria')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
