# Generated by Django 5.2.5 on 2025-08-19 11:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada_bruta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('AVISTA', 'À vista'), ('PARCELADO', 'Parcelado')], default='PARCELADO', max_length=10)),
                ('parcelas_total', models.PositiveIntegerField(default=0)),
                ('juros_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('data_inicio_parcelamento', models.DateField(blank=True, null=True)),
                ('comissao_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=8)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='vendas.venda')),
            ],
            options={
                'ordering': ['vencimento'],
                'unique_together': {('venda', 'numero')},
            },
        ),
    ]
