# Generated by Django 5.2.5 on 2025-08-20 15:17

import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=vendas.models.comprovante_parcela_path),
        ),
        migrations.AddField(
            model_name='venda',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=vendas.models.comprovante_venda_path),
        ),
    ]
