# Generated by Django 5.2.5 on 2025-08-18 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('COMISSAO', 'Comissão de Vendas'), ('CUSTO', 'Custo Operacional'), ('PESSOAL', 'Pessoal/Família'), ('FAZENDA', 'Fazenda Aprazível'), ('EMPRESA', 'Empresa (Concil)'), ('OUTRA', 'Outra')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('PAGA', 'Paga')], default='PREVISTA', max_length=8)),
                ('origem', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
