# Generated by Django 5.2.5 on 2025-08-20 15:24

import django.utils.timezone
import financeiro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="despesa",
            options={"ordering": ["-data", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="receitaextra",
            options={"ordering": ["-data", "-id"]},
        ),
        migrations.AddField(
            model_name="despesa",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="despesa",
            name="comprovante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=financeiro.models.comprovante_despesa_path,
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receitaextra",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="receitaextra",
            name="comprovante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=financeiro.models.comprovante_receita_path,
            ),
        ),
        migrations.AddField(
            model_name="receitaextra",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(fields=["data"], name="financeiro__data_54ed3b_idx"),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["categoria"], name="financeiro__categor_5d32be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(fields=["status"], name="financeiro__status_b6512e_idx"),
        ),
        migrations.AddIndex(
            model_name="receitaextra",
            index=models.Index(fields=["data"], name="financeiro__data_851a32_idx"),
        ),
    ]
