# Generated by Django 5.2.5 on 2025-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=32, unique=True)),
                ('recebe_vencimentos_hoje', models.BooleanField(default=True)),
                ('recebe_atrasados', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
